services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: csE410!
      MYSQL_DATABASE: secure_dove     
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./app
    container_name: flask_app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: csE410!
      DB_NAME: secure_dove
    ports:
      - "5000:5000" 
    depends_on:
      - db

volumes:
  db_data:
